### ISSUE TITLE
Potentially broken Orthanc URL due to server migration

### ISSUE THREAD

**Issue by luisrgpt** [opprDev/medical-image-downloader#13]
@FMCalisto Is http://breastscreening.isr.tecnico.ulisboa.pt still working? If not, do we have any alternative URL?

I've tried to demo the downloader, but it froze without downloading any medical image.

**Comment by FMCalisto** [comment]
The link is down for a while. However, I will need to put this link up again for a scientific publication. Therefore, it will be available really soon.

**Comment by FMCalisto** [comment]
The issue is now solved. Servers changed from [`breastscreening.isr.tecnico.ulisboa.pt`]( http://breastscreening.isr.tecnico.ulisboa.pt) to [`breastscreening.arditi.pt`](http://breastscreening.arditi.pt) solved by the [`3fd9a38964a4d900605fd0706ddc240813dd5229`](https://github.com/opprDev/medical-image-downloader/commit/3fd9a38964a4d900605fd0706ddc240813dd5229) commit.
