### ISSUE TITLE
Use GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by luisrgpt** [opprDev/medical-image-downloader#8]
Now that we have some unit tests, and our code refactored, we could keep passing our tests and keep our code clean. We could even further expand our test suite and ensure our code is cleaner than ever, and monitor our progress in those fields. For most of that to happen automatically, I believe we could apply CI/CD into our software.

Since we are storing this repository at GitHub, why not using GitHub Actions? It's free for FOSS, and does not require additional third-party tools.

**Comment by FMCalisto** [comment]
It seems a good idea! What do you need for that?

**Comment by luisribeirogomes** [comment]
To be honest, this is my first time using GitHub Actions. However, as far as I can see, it is pretty much straightforward. I'll first create a [workflow](https://help.github.com/en/actions/configuring-and-managing-workflows) so that the source code is tested and inspected every time a push or a pull request is made. Then we can see if it is doable to publish our code into PyPI.

**Comment by luisribeirogomes** [comment]
This repository is now, on its own, capable of testing/evaluating its code and generating packages delivered in the testing environment of PyPI. I've not yet written the workflow that GitHub Actions will use to publish our releases into the _real_ PyPI since we are going to validate what we are going to publish first.

Also, I haven't found a way, for now, to automatically increment the version of our packages at GitHub Actions. We should also address this issue before publishing releases.

**Comment by luisribeirogomes** [comment]
For now, we don't really need to automatically increment the version of our packages. Instead of that, we can simply publish our packages by tagging them through `git tag`. It is a manual task, but, in this way, we can control how and in which version we want to send our packages.

I made a POC for that to work in the testing environment of PyPI, but, if agreed, we can extend our GitHub workflow to publish the packages into [the production environment of] PyPI.

**Comment by luisrgpt** [comment]
Given some limitations from GitHub Actions, I would like to suggest this repository to be version-controlled under gitflow as well. The nomenclature of gitflow branches allows us to automatically trigger certain GitHub workflows when, for instance, a release branch has been created and published, or the master branch has a new commit.

This also gives us the liberty to migrate to alternative CI/CD tools without having to further rethink when certain CI/CD step should be triggered since the trigger is not associated with any GitHub event in particular.

A [POC](https://github.com/luisrgpt/medical-image-downloader/commit/8e92110d2bf73afb8a1b0a91362779e99cc881de) has been made on the develop branch.

**Comment by FMCalisto** [comment]
@luisrgpt could you please provide me the proper link for the PyPI published source? Thank you.

**Comment by luisrgpt** [comment]
@FMCalisto We haven't one yet. However, you can see a POC in the https://test.pypi.org/project/mi-downloader/.
